name: "Alert notification"
description: "Scans container images for vulnerabilities with Trivy"
author: "Aqua Security"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    URL: ${{ github.event.pull_request.comments_url }}
